In [1]:
import pandas as pd
from scipy import stats
import numpy as np

In [38]:
df = pd.read_csv('C:/Users/Admin/Downloads/hdb_resale_flat_transactions.csv')
df.drop(labels=['Unnamed: 0', 'blk_no', 'road_name', 'building', 'postal'], axis=1, inplace=True)
df.head()

,month,town,resale_price,storey_range,flat_type,flat_model,lease_commence_date,remaining_lease_years,remaining_lease_months,floor_area_sqm,...,y,latitude,longitude,closest_mrt_station,distance_to_mrt_meters,transport_type,line_color,distance_to_cbd,closest_pri_school,distance_to_pri_school_meters
0,2017-01-01,ANG MO KIO,232000.0,10 TO 12,2 ROOM,Improved,1979-05-01,61,4,44.0,...,38229.067463,1.362005,103.853880,Ang Mo Kio,999.941618,MRT,Red,8615.656983,TOWNSVILLE PRIMARY SCHOOL,218.125254
1,2017-01-01,ANG MO KIO,250000.0,01 TO 03,3 ROOM,New Generation,1978-08-01,60,7,67.0,...,39220.009892,1.370966,103.838202,Ang Mo Kio,1268.958246,MRT,Red,9715.131951,ANG MO KIO PRIMARY SCHOOL,241.572335
2,2017-01-01,ANG MO KIO,262000.0,01 TO 03,3 ROOM,New Generation,1980-06-01,62,5,67.0,...,40297.283149,1.380709,103.835368,Yio Chu Kang,1072.295164,MRT,Red,10828.819556,ANDERSON PRIMARY SCHOOL,777.155378
3,2017-01-01,ANG MO KIO,265000.0,04 TO 06,3 ROOM,New Generation,1980-02-01,62,1,68.0,...,38693.098657,1.366201,103.857201,Ang Mo Kio,945.371842,MRT,Red,9097.929095,TECK GHEE PRIMARY SCHOOL,698.165530
4,2017-01-01,ANG MO KIO,265000.0,01 TO 03,3 ROOM,New Generation,1980-06-01,62,5,67.0,...,40334.052030,1.381041,103.835132,Yio Chu Kang,1095.197729,MRT,Red,10869.453109,ANDERSON PRIMARY SCHOOL,782.553222

In [22]:
print('### Data Types ###\n')
df.dtypes

### Data Types ###

month                             object
postal                             int64
resale_price                     float64
storey_range                      object
flat_type                         object
flat_model                        object
lease_commence_date               object
remaining_lease_years              int64
remaining_lease_months             int64
floor_area_sqm                   float64
floor_area_sqft                  float64
price_per_sqft                   float64
planning_area_ura                 object
region_ura                        object
x                                float64
y                                float64
latitude                         float64
longitude                        float64
closest_mrt_station               object
distance_to_mrt_meters           float64
transport_type                    object
line_color                        object
distance_to_cbd                  float64
closest_pri_school                object
distance_to_pri_school_meters    float64
dtype: object

In [23]:
print('### Nulls ###\n')
print(df.isnull().sum())

### Nulls ###

month                            0
postal                           0
resale_price                     0
storey_range                     0
flat_type                        0
flat_model                       0
lease_commence_date              0
remaining_lease_years            0
remaining_lease_months           0
floor_area_sqm                   0
floor_area_sqft                  0
price_per_sqft                   0
planning_area_ura                0
region_ura                       0
x                                0
y                                0
latitude                         0
longitude                        0
closest_mrt_station              0
distance_to_mrt_meters           0
transport_type                   0
line_color                       0
distance_to_cbd                  0
closest_pri_school               0
distance_to_pri_school_meters    0
dtype: int64

In [24]:
print('Number of duplicated rows: ', df.duplicated().sum())

Number of duplicated rows:  304

In [25]:
df = df.drop_duplicates()
print('Duplicated rows after dropping: ', df.duplicated().sum())

Duplicated rows after dropping:  0

In [26]:
print('### Unique values ###\n')
print(df.nunique())

### Unique values ###

month                              103
postal                            9660
resale_price                      4424
storey_range                        17
flat_type                            7
flat_model                          21
lease_commence_date                581
remaining_lease_years               58
remaining_lease_months              12
floor_area_sqm                     184
floor_area_sqft                    184
price_per_sqft                   33887
planning_area_ura                   31
region_ura                           5
x                                 9660
y                                 9660
latitude                          9660
longitude                         9660
closest_mrt_station                136
distance_to_mrt_meters           10870
transport_type                       2
line_color                           7
distance_to_cbd                   9660
closest_pri_school                 169
distance_to_pri_school_meters     9660
dtype: int64

In [27]:
print('Shape of the dataset: ', df.shape)

Shape of the dataset:  (212397, 25)

In [28]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
postal,212397.0,563467.295805,190635.729568,50004.000000,510254.000000,560709.000000,730359.000000,8.251950e+05
resale_price,212397.0,518678.754383,183367.283083,140000.000000,381000.000000,488000.000000,620888.000000,1.658888e+06
remaining_lease_years,212397.0,73.889942,14.170541,40.000000,62.000000,74.000000,88.000000,9.700000e+01
remaining_lease_months,212397.0,5.553435,3.463198,0.000000,3.000000,6.000000,9.000000,1.100000e+01
floor_area_sqm,212397.0,96.848835,24.038244,31.000000,82.000000,93.000000,112.000000,3.667000e+02
floor_area_sqft,212397.0,1042.471180,258.745254,333.680900,882.639800,1001.042700,1205.556800,3.947122e+03
price_per_sqft,212397.0,502.829235,146.383822,194.125943,399.344797,477.242106,569.536579,1.500287e+03
x,212397.0,28882.830927,7901.184146,11519.146494,22117.569163,29448.377084,35280.238691,4.519230e+04
y,212397.0,38913.395777,4750.086544,28097.635137,35507.734672,38860.879963,42077.035325,4.874106e+04
latitude,212397.0,1.368192,0.042958,1.270380,1.337394,1.367715,1.396803,1.457071e+00
longitude,212397.0,103.841251,0.070997,103.685228,103.780459,103.846334,103.898737,1.039878e+02
distance_to_mrt_meters,212397.0,621.728779,386.887857,22.606499,323.034417,545.060251,830.609887,3.496416e+03
distance_to_cbd,212397.0,12388.897275,4382.901235,585.558618,9665.741932,13319.319685,15375.595121,2.012107e+04
distance_to_pri_school_meters,212397.0,420.261273,256.462000,42.554863,235.947244,369.242264,537.954557,3.306003e+03

In [37]:
num_cols = df.select_dtypes(['int64', 'float64']).columns.tolist()
for col in num_cols:
    max_ = np.max(df[col])
    min_ = np.min(df[col])
    ranges = max_ - min_
    print(f'Range of {col}: %.2f' %ranges)

Range of postal: 775191.00
Range of resale_price: 1518888.00
Range of remaining_lease_years: 57.00
Range of remaining_lease_months: 11.00
Range of floor_area_sqm: 335.70
Range of floor_area_sqft: 3613.44
Range of price_per_sqft: 1306.16
Range of x: 33673.15
Range of y: 20643.42
Range of latitude: 0.19
Range of longitude: 0.30
Range of distance_to_mrt_meters: 3473.81
Range of distance_to_cbd: 19535.51
Range of distance_to_pri_school_meters: 3263.45

In [39]:
df.to_csv('csv_file_transformed.csv', index=False)