*Dataset From Kaggle:* https://www.kaggle.com/datasets/vinothkannaece/sales-dataset

In [58]:
#To import/load the dataset here, we have to import Pandas first. So let's import it.
import pandas as pd

#Importing/loading the dataset(.csv). Make sure you wrote the directory name correctly.
data = pd.read_csv('C:/Users/Admin/Downloads/sales_data.csv')
data.head(5)

#By the way, you can also see the whole dataset. In that case, you won't have to write ".head()". Just use "data". And you can also 
#put the number of how many rows you want to see.

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [32]:
#If you want to know how many columns and row exist in the dataset, write the following:
print('Row: ',data.shape[0], '\nColumn: ', data.shape[1])

#Or you can put like this:
print('\nShape of the dataset: ', data.shape) 

#Remember I used '\n' to create a gap in the middle vertically.

Row:  1000
Column:  14

Shape of the dataset:  (1000, 14)

In [27]:
#Check how many columns contain numbers and object:

num_cols = data.select_dtypes(['int64', 'float64']).columns.tolist()
obj_cols = data.select_dtypes(['object']).columns.tolist()

print('Num Cols: ', len(num_cols), '\nObject Cols: ', len(obj_cols))

Num Cols:  6
Object Cols:  8

In [30]:
#You can use info to get more information about the dataset you're working with. See below:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   object
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB
None

***Now we will generate some basic summary statistics from our dataset, so we are going to work with columns that contain numbers. We are not including Product_ID for it does not contain any useful data that can be used to produce any useful information.***

*We will be analyzing mean, median, mode, variance, standard deviation(std), range, percentile, quartile, and interquartile range(IQR).*

In [53]:
#To generate summary statistics, we have to import Numpy and Stats from Scipy
import numpy as np
from scipy import stats

#Let's select the columns that contain useful numbers and drop 'Product_ID':

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()
print('Num Cols: ', num_cols)

Num Cols:  ['Sales_Amount', 'Quantity_Sold', 'Unit_Cost', 'Unit_Price', 'Discount']

In [97]:
#Mean is average value of a numeric column. It answers one simple question, and that is: if all vaues were evenly distributed, 
#what would the typical value be? It is calculated by (Sum of all values/Number of values). If a value is extremely high or 
#low (which is an outlier),it directly increases or decreases the sum, thus shifting the mean.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Mean ({col}): ',np.mean(data[col]))

Mean (Sales_Amount):  5019.265229999999
Mean (Quantity_Sold):  25.355
Mean (Unit_Cost):  2475.3045500000003
Mean (Unit_Price):  2728.44012
Mean (Discount):  0.15239

In [98]:
#Median is the middle value of a numeric column when sorted in order. If the mean is unusually larger or lower than median, then
#potential outliers exist in the dataset that we are working with.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Median ({col}): ',np.median(data[col]))

Median (Sales_Amount):  5019.3
Median (Quantity_Sold):  25.0
Median (Unit_Cost):  2467.2349999999997
Median (Unit_Price):  2696.4
Median (Discount):  0.15

In [99]:
#Mode is the particular value that appears most frequently in a column. However mode can be used for both numeric and object/categorical column.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Mode ({col}): ',stats.mode(data[col])[0])

Mode (Sales_Amount):  6116.75
Mode (Quantity_Sold):  47
Mode (Unit_Cost):  666.84
Mode (Unit_Price):  167.12
Mode (Discount):  0.22

In [100]:
#Variance is a masure of how spread out the numbers in a numeric column are from the mean. It answers the question of how far do the
#the values typically deviate from the average value.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Variance ({col}): ',np.var(data[col]))

Variance (Sales_Amount):  8096109.80558255
Variance (Quantity_Sold):  200.276975
Variance (Unit_Cost):  2008352.1941553971
Variance (Unit_Price):  2012681.2058611838
Variance (Discount):  0.007596187899999976

In [101]:
#Standard deviation is the square root of variance. Same as variance, but the result is back in the original units of the data.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Standard deviation ({col}): ',np.std(data[col]))

Standard deviation (Sales_Amount):  2845.366374578597
Standard deviation (Quantity_Sold):  14.15192478074979
Standard deviation (Unit_Cost):  1417.1634324083434
Standard deviation (Unit_Price):  1418.6899611476722
Standard deviation (Discount):  0.08715611223545928

In [102]:
#Range is the difference between the largest value and the smallest value in a dataset. A single extremely high or low value
#can make the range very high, which also suggest the range is sensetive to outliers.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    max_ = np.max(data[col])
    min_ = np.min(data[col])
    range_ = max_ - min_
    print(f'Range ({col}): ',range_)

Range (Sales_Amount):  9888.92
Range (Quantity_Sold):  48
Range (Unit_Cost):  4935.02
Range (Unit_Price):  5275.03
Range (Discount):  0.3

In [103]:
#Percentile is the value below which a certain percentage of the data falls. It divides the numbers in a numeric column into
#100 equal parts. 50th percentile is the value such that 50% of the data are below it.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Percentile 60 ({col}): ',np.percentile(data[col],60))

Percentile 60 (Sales_Amount):  6063.632
Percentile 60 (Quantity_Sold):  30.0
Percentile 60 (Unit_Cost):  2930.66
Percentile 60 (Unit_Price):  3195.748
Percentile 60 (Discount):  0.19

In [104]:
#Quartile is the same as percentile, but it divides a dataset into 4 equal parts.

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Quartile 75 ({col}): ',np.quantile(data[col], .75))

Quartile 75 (Sales_Amount):  7507.445000000001
Quartile 75 (Quantity_Sold):  38.0
Quartile 75 (Unit_Cost):  3702.8650000000002
Quartile 75 (Unit_Price):  3957.9700000000003
Quartile 75 (Discount):  0.23

In [105]:
#Interquartile range(IQR) is basically the range of the middle 50% of a particular numeric column or data which 
#is "Q2(percentile 75th) - Q1(percentile 25th)"

num_cols = num_cols = data.select_dtypes(['int64', 'float64']).drop('Product_ID', axis=1).columns.tolist()

for col in num_cols:
    print(f'Interquartile Range ({col}): ',stats.iqr(data[col]))

Interquartile Range (Sales_Amount):  4957.147500000001
Interquartile Range (Quantity_Sold):  25.0
Interquartile Range (Unit_Cost):  2464.4850000000006
Interquartile Range (Unit_Price):  2448.885
Interquartile Range (Discount):  0.15000000000000002

In [106]:
#Describe is like a quick stats snapshot of the dataset (e.g., count, mean, std etc.)
data[num_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Sales_Amount,1000.0,5019.26523,2846.790126,100.12,2550.2975,5019.300,7507.445,9989.04
Quantity_Sold,1000.0,25.35500,14.159006,1.00,13.0000,25.000,38.000,49.00
Unit_Cost,1000.0,2475.30455,1417.872546,60.28,1238.3800,2467.235,3702.865,4995.30
Unit_Price,1000.0,2728.44012,1419.399839,167.12,1509.0850,2696.400,3957.970,5442.15
Discount,1000.0,0.15239,0.087200,0.00,0.0800,0.150,0.230,0.30

In [107]:
#Correlation is a measure of how two variables are related to each other. It tells us whether and how strongly one variable changes
#when another changes.

data[num_cols].corr().T

               Sales_Amount  Quantity_Sold  Unit_Cost  Unit_Price  Discount
Sales_Amount       1.000000      -0.041599   0.009770    0.011812  0.023153
Quantity_Sold     -0.041599       1.000000   0.053888    0.057296 -0.007806
Unit_Cost          0.009770       0.053888   1.000000    0.995056 -0.017741
Unit_Price         0.011812       0.057296   0.995056    1.000000 -0.017027
Discount           0.023153      -0.007806  -0.017741   -0.017027  1.000000